env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:ava/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
rules:
  no-underscore-dangle:
    - 0
  space-before-function-paren:
    - error
    - always
  strict:
    - error
    - global
  no-console:
    - 0
  array-bracket-spacing:
    - error
    - always
    - objectsInArrays: false
      arraysInArrays: false
  max-len:
    - error
    - 200
    - 2
    - ignoreUrls: true
      ignoreComments: false
      ignoreRegExpLiterals: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
  object-curly-newline:
    - error
    - ObjectExpression:
        minProperties: 6
        multiline: true
        consistent: true
      ObjectPattern:
        minProperties: 6
        multiline: true
        consistent: true
      ImportDeclaration:
        minProperties: 6
        multiline: true
        consistent: true
      ExportDeclaration:
        minProperties: 6
        multiline: true
        consistent: true
